-- Export données Douéra Shop
-- À importer dans votre nouvelle base PostgreSQL


-- TABLES
CREATE TABLE IF NOT EXISTS users (id TEXT PRIMARY KEY, email TEXT UNIQUE, password TEXT, name TEXT, role TEXT, status TEXT, address TEXT, phone TEXT);
CREATE TABLE IF NOT EXISTS products (id TEXT PRIMARY KEY, name TEXT, price INTEGER, category TEXT, image TEXT, stock INTEGER, description TEXT, specs TEXT, media TEXT);
CREATE TABLE IF NOT EXISTS orders (id TEXT PRIMARY KEY, userId TEXT, date TEXT, method TEXT, status TEXT, total INTEGER, items TEXT, customer_firstname TEXT, customer_lastname TEXT, customer_address TEXT, customer_phone TEXT, review_id TEXT);
CREATE TABLE IF NOT EXISTS reviews (id TEXT PRIMARY KEY, orderId TEXT, productId TEXT, userId TEXT, userName TEXT, rating_product INTEGER, rating_service INTEGER, comment TEXT, admin_reply TEXT, date TEXT);


-- USERS (9 entrées)
INSERT INTO users (id, email, password, name, role, status, address, phone) VALUES ('u1', 'admin@douerashop.sn', 'admin123', 'Super Admin', 'super_admin', 'active', NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO users (id, email, password, name, role, status, address, phone) VALUES ('u2', 'demo@douerashop.sn', 'password123', 'Admin Démo', 'admin', 'active', NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO users (id, email, password, name, role, status, address, phone) VALUES ('u1776682085568', 'mcb@douerashop.sn', 'Code123', 'mcb', 'client', 'active', 'Lao Demba', '764027468') ON CONFLICT (id) DO NOTHING;
INSERT INTO users (id, email, password, name, role, status, address, phone) VALUES ('u1776771310408', 'bayefall@douerashop.sn', 'Code123', 'Baye Fall', 'client', 'active', 'Thiaroye sur mer', '78 160 74 68') ON CONFLICT (id) DO NOTHING;
INSERT INTO users (id, email, password, name, role, status, address, phone) VALUES ('u1776789726415', 'fox@douerashop.sn', 'Code123', 'Fox', 'client', 'active', NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO users (id, email, password, name, role, status, address, phone) VALUES ('u1777290171868', 'capo@douerashop.sn', 'Code123', 'Mohamed Fall', 'client', 'active', 'HLM', '78 123 45 67') ON CONFLICT (id) DO NOTHING;
INSERT INTO users (id, email, password, name, role, status, address, phone) VALUES ('u1777293978065', 'cheikh@douerashop.sn', 'Codfe123', 'cheikh ba', 'client', 'active', 'HLM', '77 025 01 95') ON CONFLICT (id) DO NOTHING;
INSERT INTO users (id, email, password, name, role, status, address, phone) VALUES ('u1777294516467', 'aly@douerashop.sn', 'Code123', 'Aly Mbaye', 'client', 'active', 'Sinthiane', '77 000 00 00') ON CONFLICT (id) DO NOTHING;
INSERT INTO users (id, email, password, name, role, status, address, phone) VALUES ('u1777370333314', 'dame@douerashop.sn', 'Code123', 'Dame Mbodji', 'client', 'active', 'Thiès', '77 123 45 67') ON CONFLICT (id) DO NOTHING;

-- PRODUCTS (9 entrées)
INSERT INTO products (id, name, price, category, image, stock, description, specs, media) VALUES ('p1', 'iPhone 11 Pro 64Go', '280000', 'Téléphone', 'assets/Apple-iPhone-11-Pro-64-Go-5-8-Gris-Sideral-5.jpg', '8', 'Iphone 11 Pro 64Go venant d''USA Grade A++. 
Batterie d''origine 95%
Chargeur offert.
Un produit d''exception.', NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id, name, price, category, image, stock, description, specs, media) VALUES ('p2', 'iPhone XR 128Go', '175000', 'Téléphone', 'assets/Iphone XR.jpeg', '5', 'Un produit d''exception.', NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id, name, price, category, image, stock, description, specs, media) VALUES ('p3', 'iPhone XR 64Go', '150000', 'Téléphone', 'assets/Iphone XR.jpg', '4', 'Un produit d''exception.', NULL, '[]') ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id, name, price, category, image, stock, description, specs, media) VALUES ('p4', 'iPhone 11 Simple', '220000', 'Téléphone', 'assets/iPhone11_Visuel1-DM.webp', '2', 'Un produit d''exception.', NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id, name, price, category, image, stock, description, specs, media) VALUES ('p5', 'Bracelets Luxe', '5000', 'Mode', 'assets/Bracelet.webp', '16', 'Un produit d''exception.', NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id, name, price, category, image, stock, description, specs, media) VALUES ('p6', 'Colliers Élégance', '12000', 'Luxe', 'assets/Colier.webp', '14', 'Un produit d''exception.', NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id, name, price, category, image, stock, description, specs, media) VALUES ('p7', 'Gants pour sport Pro', '7500', 'Sport', 'assets/Gantdesporthomme_1.webp', '16', 'Un produit d''exception.', NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id, name, price, category, image, stock, description, specs, media) VALUES ('p8', 'Chaussure de Sport Nike', '35000', 'Sport', 'assets/Chaussure nike.jpg', '6', 'Un produit d''exception.', NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id, name, price, category, image, stock, description, specs, media) VALUES ('p1783096068489', 'iPhone 13 128Go', '170000', 'Téléphone', 'assets/electronics_1.png', '6', 'iPhone 13', NULL, '[{"type": "video", "url": "https://www.youtube.com/shorts/4ce8T"}]') ON CONFLICT (id) DO NOTHING;

-- ORDERS (13 entrées)
INSERT INTO orders (id, userId, date, method, status, total, items, customer_firstname, customer_lastname, customer_address, customer_phone, review_id) VALUES ('ORD-1777293532', 'u1777290171868', '2026-04-27T12:38:52.403Z', 'card', 'En attente', '5000', '[{"category": "Mode", "description": "Un produit d''exception.", "id": "p5", "image": "assets/Bracelet.webp", "name": "Bracelets Luxe", "price": 5000, "stock": 21, "quantity": 1}]', 'Mohamed', 'Fall', 'HLM', '77 134 65 65', NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO orders (id, userId, date, method, status, total, items, customer_firstname, customer_lastname, customer_address, customer_phone, review_id) VALUES ('ORD-1777294018', 'u1777293978065', '2026-04-27T12:46:58.249Z', 'cash', 'En attente', '350000', '[{"category": "T\u00e9l\u00e9phone", "description": "Un produit d''exception.", "id": "p2", "image": "assets/Iphone XR.jpeg", "name": "iPhone XR 128Go", "price": 175000, "stock": 6, "quantity": 2}]', 'cheikh', 'ba', 'HLM', '77 025 01 95', NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO orders (id, userId, date, method, status, total, items, customer_firstname, customer_lastname, customer_address, customer_phone, review_id) VALUES ('ORD-1777295036', 'u1777293978065', '2026-04-27T13:03:55.993Z', 'cash', 'En attente', '5000', '[{"category": "Mode", "description": "Un produit d''exception.", "id": "p5", "image": "assets/Bracelet.webp", "name": "Bracelets Luxe", "price": 5000, "stock": 20, "quantity": 1}]', 'cheikh', 'ba', 'HLM', '77 025 01 95', NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO orders (id, userId, date, method, status, total, items, customer_firstname, customer_lastname, customer_address, customer_phone, review_id) VALUES ('ORD-1777307714', 'u1777290171868', '2026-04-27T16:35:14.487Z', 'card', 'En attente', '280000', '[{"category": "T\u00e9l\u00e9phone", "description": "Iphone 11 Pro 64Go venant d''USA Grade A++. \nBatterie d''origine 95%\nChargeur offert.\nUn produit d''exception.", "id": "p1", "image": "assets/Apple-iPhone-11-Pro-64-Go-5-8-Gris-Sideral-5.jpg", "name": "iPhone 11 Pro 64Go", "price": 280000, "stock": 10, "quantity": 1}]', 'Mohamed', 'Fall', 'HLM', '78 123 45 67', NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO orders (id, userId, date, method, status, total, items, customer_firstname, customer_lastname, customer_address, customer_phone, review_id) VALUES ('ORD-1777308567', 'u1776771310408', '2026-04-27T16:49:27.558Z', 'wave', 'Livré', '392500', '[{"category": "T\u00e9l\u00e9phone", "description": "Un produit d''exception.", "id": "p2", "image": "assets/Iphone XR.jpeg", "name": "iPhone XR 128Go", "price": 175000, "stock": 5, "quantity": 2}, {"category": "Sport", "description": "Un produit d''exception.", "id": "p7", "image": "assets/Gantdesporthomme_1.webp", "name": "Gants pour sport Pro", "price": 7500, "stock": 17, "quantity": 1}, {"category": "Sport", "description": "Un produit d''exception.", "id": "p8", "image": "assets/Chaussure nike.jpg", "name": "Chaussure de Sport Nike", "price": 35000, "stock": 7, "quantity": 1}]', 'Baye', 'Fall', 'Thiaroye sur mer', '78 160 74 68', NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO orders (id, userId, date, method, status, total, items, customer_firstname, customer_lastname, customer_address, customer_phone, review_id) VALUES ('ORD-1777309261', 'u1776771310408', '2026-04-27T17:01:01.689Z', 'cash', 'Livré', '160000', '[{"category": "Mode", "description": "Un produit d''exception.", "id": "p5", "image": "assets/Bracelet.webp", "name": "Bracelets Luxe", "price": 5000, "specs": null, "stock": 19, "quantity": 2}, {"category": "T\u00e9l\u00e9phone", "description": "Un produit d''exception.", "id": "p3", "image": "assets/Iphone XR.jpg", "name": "iPhone XR 64Go", "price": 150000, "specs": null, "stock": 8, "quantity": 1}]', 'Baye', 'Fall', 'Thiaroye sur mer', '78 160 74 68', NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO orders (id, userId, date, method, status, total, items, customer_firstname, customer_lastname, customer_address, customer_phone, review_id) VALUES ('TEST-ORDER-123', 'u1776682085568', '2026-04-27T17:19:35.142065', 'wave', 'Livrée', '280000', '[{"id": "p1", "name": "iPhone 11 Pro 64Go", "price": 280000, "quantity": 1, "image": "assets/electronics_1.png"}]', 'Moussa', 'Test', 'Quartier Escale, Douéra', '781234567', NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO orders (id, userId, date, method, status, total, items, customer_firstname, customer_lastname, customer_address, customer_phone, review_id) VALUES ('ORD-1777310543', 'u1776682085568', '2026-04-27T17:22:23.050Z', 'wave', 'Livré', '395000', '[{"category": "T\u00e9l\u00e9phone", "description": "Un produit d''exception.", "id": "p2", "image": "assets/Iphone XR.jpeg", "name": "iPhone XR 128Go", "price": 175000, "specs": null, "stock": 3, "quantity": 1}, {"category": "T\u00e9l\u00e9phone", "description": "Un produit d''exception.", "id": "p4", "image": "assets/iPhone11_Visuel1-DM.webp", "name": "iPhone 11 Simple", "price": 220000, "specs": null, "stock": 4, "quantity": 1}]', 'mcb', '', 'Lao Demba', '76 402 74 68', NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO orders (id, userId, date, method, status, total, items, customer_firstname, customer_lastname, customer_address, customer_phone, review_id) VALUES ('ORD-1777312269', 'u1776682085568', '2026-04-27T17:51:09.886Z', 'orange', 'Livré', '175000', '[{"category": "T\u00e9l\u00e9phone", "description": "Un produit d''exception.", "id": "p2", "image": "assets/Iphone XR.jpeg", "name": "iPhone XR 128Go", "price": 175000, "specs": null, "stock": 2, "quantity": 1}]', 'mcb', '', 'Lao Demba', '764027468', NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO orders (id, userId, date, method, status, total, items, customer_firstname, customer_lastname, customer_address, customer_phone, review_id) VALUES ('ORD-1777368020', 'u1776682085568', '2026-04-28T09:20:20.192Z', 'orange', 'Livré', '180000', '[{"category": "T\u00e9l\u00e9phone", "description": "Un produit d''exception.", "id": "p2", "image": "assets/Iphone XR.jpeg", "name": "iPhone XR 128Go", "price": 175000, "specs": null, "stock": 1, "quantity": 1}, {"category": "Mode", "description": "Un produit d''exception.", "id": "p5", "image": "assets/Bracelet.webp", "name": "Bracelets Luxe", "price": 5000, "specs": null, "stock": 17, "quantity": 1}]', 'mcb', '', 'Lao Demba', '764027468', NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO orders (id, userId, date, method, status, total, items, customer_firstname, customer_lastname, customer_address, customer_phone, review_id) VALUES ('ORD-1777369593', 'u1776682085568', '2026-04-28T09:46:33.049Z', 'cash', 'Livré', '220000', '[{"category": "T\u00e9l\u00e9phone", "description": "Un produit d''exception.", "id": "p4", "image": "assets/iPhone11_Visuel1-DM.webp", "name": "iPhone 11 Simple", "price": 220000, "specs": null, "stock": 3, "quantity": 1}]', 'mcb', '', 'Lao Demba', '764027468', NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO orders (id, userId, date, method, status, total, items, customer_firstname, customer_lastname, customer_address, customer_phone, review_id) VALUES ('ORD-1777370457', 'u1777370333314', '2026-04-28T10:00:57.511Z', 'orange', 'Livré', '280000', '[{"category": "T\u00e9l\u00e9phone", "description": "Iphone 11 Pro 64Go venant d''USA Grade A++. \nBatterie d''origine 95%\nChargeur offert.\nUn produit d''exception.", "id": "p1", "image": "assets/Apple-iPhone-11-Pro-64-Go-5-8-Gris-Sideral-5.jpg", "name": "iPhone 11 Pro 64Go", "price": 280000, "specs": null, "stock": 9, "quantity": 1}]', 'Dame', 'Mbodji', 'Thiès', '77 123 45 67', NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO orders (id, userId, date, method, status, total, items, customer_firstname, customer_lastname, customer_address, customer_phone, review_id) VALUES ('ORD-DEMO-99', 'u_demo', '1777457575855', 'Wave', 'En attente', '350000', '[{"id": "p1", "name": "iPhone 11 Pro", "price": 350000, "quantity": 1, "image": "assets/electronics_1.png"}]', 'Client', 'Démo', 'Dakar, Plateau', '770000000', NULL) ON CONFLICT (id) DO NOTHING;

-- REVIEWS (1 entrées)
INSERT INTO reviews (id, orderId, productId, userId, userName, rating_product, rating_service, comment, date, admin_reply) VALUES ('rev-1777368139', 'TEST-ORDER-123', NULL, 'u1776682085568', 'mcb', '5', '4', 'Merci pour la bonne prise en charge', '2026-04-28T09:22:19.647702', 'je vous en prie c''est avec plaisir de vous servir.
DOUERA SHOP votre fidèle serviteur. N''hésiter pas si vous avez d''autres commandes notre boutique est là pour vous servir et vous satisfaire.') ON CONFLICT (id) DO NOTHING;